// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// These browser-safe credentials intentionally point every deployment to the
// project's single Supabase backend.
const SUPABASE_URL = 'https://kajrforgzdgsohvwnidu.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = 'sb_publishable_q4uapdSqQzAI4TQOk0XAZA_4YV33H81';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
